api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "fcd89a216e911e2244e643c0c8777c3903d5c32100805d336d24aa5eaa58659d"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "ad3301beaad409ad8c8383673ed66ca24997b04747105e17af4b7fcf7fcd5b05"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.48-any-stack-fcd89a21.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "3dbc6304d5586f85579060f72175c8074a6618a304ce786a0fabde721fd2b22d"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "919e8181c9988e861d9f0eff33872163f398e16f799190e3a460679c26a9a068"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.43-any-stack-3dbc6304.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "d3dbc336c35ca5d9b0809f691afef80869a795c3b711fa3270eba2b81a83e489"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "698ea1efed2f5193d74caa450b35135178de0bf8179dcf44ada82baf4c1b7e5e"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.41-any-stack-d3dbc336.tgz"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.48"
