api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "04bc3269d1ff2ea02220948e988816e57cb40ea95d575a685a3bbb58897be0ef"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "8f2adbab53b0c9bb25234d0ee2cac3014be74ca0e7a0482893fe6e57fb919f04"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.31-any-stack-04bc3269.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "9facd3fa907d1bb0950dbed392753bd055dbd9b373178e3cd8b8465806d3f675"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "fd2200cb0c883287d1d673dd7d44533905176a07211117123c51eb4a7c2c84fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.34-any-stack-9facd3fa.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "67889dfea3fe2fb90f80213844b010e3e457a0b0c232eccf9d69066ae07e29df"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "529032294ca85a784de716aee5e87265b8bd25cc75093733ce2a8dc70829a02c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.30-any-stack-67889dfe.tgz"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.31"
