api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "5e2b3e5b94333a44d362fe4f4c560aa860063ddd6fc662315a5915e948b802f5"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "423dcf0997bc92f2a5caa7330eddd8ceeb9212a02c53365f8c18247ee7b4e062"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.94-any-stack-5e2b3e5b.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "9a4d004299de3477bdf75ef41492b71d5a0a92388a8a3fda49d7d53c5796c90e"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "03c9ee306b38dac7996eda3df0e7ebc6e9e591289f4aaf09137082e02090ee50"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.88-any-stack-9a4d0042.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2cc28d64e2ee1954755532699db3acd55ab25282af0c05a7f075bddcb400c836"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "19cf73ee26a0c2dd7cc5b1b69868a2fc57c978151be8d6616cd1fc04de9c206b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.84-any-stack-2cc28d64.tgz"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.88"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.88"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.94"
