api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "5cc30eac9382b66b0c9546cf27449b55cef3c2ec657eca76550b90f0b41a220e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "a496ee8b3325987761f38b9ebab451e1793d371aa221391b3a3d80b7f559451c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.72-any-stack-5cc30eac.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "6bbe35bb66ec033d711f8d3a9cc367da493638101f1c332332a02c06488d0314"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "6431a255c9cbc60a5463e6f2d66e077af78f38898cc1fb1f5328635a2191ea17"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.63-any-stack-6bbe35bb.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "d6b6aad161e4eacbd21347f97e69f43248189fe1de002bb366a58d48dcec57cb"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "15cbc0b0adb5f415b722b9f75b54927cb738f383e9b2265e733803d2fcd36088"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.66-any-stack-d6b6aad1.tgz"
    version = "0.0.66"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.63"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.66"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.63"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.72"
