api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "7b0f0bbaf9e6fe8746193cd521716327de4548646ffebb15afdfa8f17e06274e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "479cdc027d37b710c888de1427d4628983e3d2fe738cd6edff04aea3705a288d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.65-any-stack-7b0f0bba.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "89eee1a24ba51e9e44c1418f820a3dde1e065e0a3dfb20a3659d7e21cd2521fa"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "13cd26becb885a7738aeebb784a9403c4aab027fde7cac4ac4109a956554ea5c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.55-any-stack-89eee1a2.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "ee4696ebac9e681d487cb1a4d7efd16d76faca119a9026cc8c14a88f9f9093a2"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "4c2903f555eb05a901bc81297e4b42a4aa803c985f1ad3076d2306f888ac0b52"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.59-any-stack-ee4696eb.tgz"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.55"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.55"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.65"
