api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "450cb25423148825082bd70e14e38c48e722e51b81cb3e09878d9cd3a7ddee6e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "549fb51922941aa27fd5fbe024bca36856b308395e1ec5412030bcbd7fa5214d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.89-any-stack-450cb254.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "4a52b808ea6a2a1eea39c2bfe7adb4167ea152f37202f69b17af66f75a919f23"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "aa56b57a4ed5255214c1bb779e4e26da3f33a116cb4f750652d40dc6b7298bf9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.81-any-stack-4a52b808.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2cc28d64e2ee1954755532699db3acd55ab25282af0c05a7f075bddcb400c836"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "19cf73ee26a0c2dd7cc5b1b69868a2fc57c978151be8d6616cd1fc04de9c206b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.84-any-stack-2cc28d64.tgz"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.81"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.81"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.89"
