api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "7b0f0bbaf9e6fe8746193cd521716327de4548646ffebb15afdfa8f17e06274e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "479cdc027d37b710c888de1427d4628983e3d2fe738cd6edff04aea3705a288d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.65-any-stack-7b0f0bba.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "ddb69b94ed65aedafdce547e4374f2c2663317590f79b80a093e0e4a61f27f53"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "810cbd0eb2e0fcf5f4e9142274828feca8412feee13ce18de9fd7a3894fe3ba9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.56-any-stack-ddb69b94.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "e87a09e31d25ce50ae4fdef43bb54fec25888b1865d4f9e0f541cb74b1b01a44"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "e5661b088493897462f46820241b47419273a170345a964a40033984e7827930"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.60-any-stack-e87a09e3.tgz"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.56"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.56"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.65"
