api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "4e95d661ae1c8a77eba440f9bf3c41d3fc4225861b0eb5212251fe706e8ec535"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "76c6e111103358db08f04200eaa1de34b2656c0935936810a15d125f170f3a65"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.71-any-stack-4e95d661.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "b43a51616e05b941b592976b221e43a1c8afa541c0b0b6ae6ca5b28a9a8cf6f7"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "d9d1659829a105780466db411f341762d85ff92a59bbd9c7af1fa90ac86ef583"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.62-any-stack-b43a5161.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2072dac486b5fc1e2748d3d305704f4a42db4a6e3e262034ab00e0a608458838"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "45fe8fb2095fb18027a603f162396afb430fbee37196d758e3cdad1f54c75edd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.65-any-stack-2072dac4.tgz"
    version = "0.0.65"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.62"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.65"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.62"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.71"
