api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "32db0f1d682340e99ef9831a3ebbb07c148a1704a06d6c74758b68d75121c01f"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "1a28fab05cd157a5da5e792c6d0a3d06700162c17fc2da4332d31526d5ce474f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.82-any-stack-32db0f1d.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "395fcf0546f956c21e476aa66134d11e62eb67d375a48b8df125b88616eddfbc"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "3fabf946cf763107709aa81fffa30c59b5e49c43f8c98532fbb3629d9ba0674a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.72-any-stack-395fcf05.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "7b80dc555585c76bce535ab1b113e465c84eaf4788e0edfc6abcac4643358a63"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "0d46a6f6c117bf3eae25e57f958a1c1ac392cefa6f0b43ecaa097919a7e9355d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.76-any-stack-7b80dc55.tgz"
    version = "0.0.76"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.72"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.76"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.72"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.82"
