api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "04bc3269d1ff2ea02220948e988816e57cb40ea95d575a685a3bbb58897be0ef"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "8f2adbab53b0c9bb25234d0ee2cac3014be74ca0e7a0482893fe6e57fb919f04"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.31-any-stack-04bc3269.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "9facd3fa907d1bb0950dbed392753bd055dbd9b373178e3cd8b8465806d3f675"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "fd2200cb0c883287d1d673dd7d44533905176a07211117123c51eb4a7c2c84fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.34-any-stack-9facd3fa.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "e9e66f33430b34a1475aa36f8c223c4ca7234ad6b07caad84fede27d71a9381f"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "5c90397b43930e437818821740c27d04815a48a4dc90004d3df0f0ec696b032d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.31-any-stack-e9e66f33.tgz"
version = "0.0.31"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.31"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.31"
