api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a61c7dd8d13be140806c8b8ae520354650cb323aa7970ff33407cd7e70e791d5"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "cb3607b6772b425366526e8e0230aba5c943db4f74dd438da719826c63fc6821"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.96-any-stack-a61c7dd8.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "8945618f64088679f47a17227e4f1305694aa44aa9ac26e8f34efc357b15c8c5"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "4511295e88865a2eb90a2c4c37b86d306032b3a3eaf6836b491709ac7b28c1d5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.93-any-stack-8945618f.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2cc28d64e2ee1954755532699db3acd55ab25282af0c05a7f075bddcb400c836"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "19cf73ee26a0c2dd7cc5b1b69868a2fc57c978151be8d6616cd1fc04de9c206b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.84-any-stack-2cc28d64.tgz"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.93"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.93"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.96"
