api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "1835cda115ce14a658ce5770f0030488815d7f73ee88c58cb0aa5e239f3bb5ee"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "a31198e8702f13ec0499f9196f2c2705a82478ade66cc7e1ac1b0086b0d1f805"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.47-any-stack-1835cda1.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "3dbc6304d5586f85579060f72175c8074a6618a304ce786a0fabde721fd2b22d"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "919e8181c9988e861d9f0eff33872163f398e16f799190e3a460679c26a9a068"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.43-any-stack-3dbc6304.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "c64c20a29ac74ef5c83561328dc50b917a77d93d732704a4b22a424a910d6cda"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "4707c1861e0637ac91922546e8ef71ce77ad24af96125ec1b477f7b9f5cc0fb2"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.40-any-stack-c64c20a2.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.47"
