api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "7c75ff960e63e4ceb4ced0dfd43e2a23407276b90cb14a8697db80664e01479c"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "854bb6e005aedba6b005498f86691ed239b96385d5ff25e5bf9ef19830b57198"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.44-any-stack-7c75ff96.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "5632bc952dfc9073576adffef5eb5d0a116658bed8905fb347bdbde0bc797ba7"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "de091958da904431e88ef0b87eb84ca800e1dfbbdb94736141f9c95fd9416a7d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.40-any-stack-5632bc95.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "f58c188e3c6662da7bbef5728b0def042d0ec234e1d93e14108b9e037892fe97"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "62f53d9266f74afe5f7f116551fe4b58f887cd1fbfcaced06dc40e0f98831f3b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.36-any-stack-f58c188e.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.44"
