api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "87a496cdb068e84a5a0f68c4a69fbc225b60053e09b2c8e58866a15a1b05bbbd"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "8433b53885c5d81db995dd607656d5cd1ff7c9015dfc5a32452390ff7d1ed42a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.100-any-stack-87a496cd.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "121bab77dcf470b5a9aa568e03f554e475b2a4515f60d62d6bd882a625258807"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "db3b2b82e362959718033d36d5a8ca7a53b2c9592b90087e819a5c0d20dee60e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.100-any-stack-121bab77.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "34b8acf294a7d36ab92575eb0b4fa334250d700126d20397e8f6604ea627b0ed"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "99ac081b75148214d71dd4580a2d99e7efdc6c4ea45903c70d9cb93410c4ae95"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.86-any-stack-34b8acf2.tgz"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.100"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.100"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.100"
