api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "0120c1e97c4dcef41de6f768ae508a6c0c38511e1779fd44aa40994209e0b879"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "b7b4c0ecc48854ae0bd1f12ba0f5f20c28ce2b353af7528cd06e37714ffa0d98"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.95-any-stack-0120c1e9.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "9ed6c14267c02ca707ccc3fc04a78ff32e41c36d19a8a4b720058cd8fe78c10c"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "8328dc5b10d5cab5ea74bd68494d3299d650b4ebb5cf3e26d0ea0023112c2e20"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.90-any-stack-9ed6c142.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2cc28d64e2ee1954755532699db3acd55ab25282af0c05a7f075bddcb400c836"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "19cf73ee26a0c2dd7cc5b1b69868a2fc57c978151be8d6616cd1fc04de9c206b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.84-any-stack-2cc28d64.tgz"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.95"
