api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "fd8af9a737879e273de30fb09f1447ff126125f2b48cfe7fa68426755cfb3bae"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.109.tar.gz"
    source_sha256 = "ed0b71d9798ceae94d1c41a04e1e70751608c36f261a7f277d1d0b201898211d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.109_linux_noarch_any-stack_fd8af9a7.tgz"
    version = "0.0.109"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a243a85f507ee9bf8f9c9e24f521362816e1f0b5204a724861066ab3953b77a8"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "22c8df59a80cfc5b53973f32412b4917f3e1d689f3801e588430bd7ec6afb1d6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.111_linux_noarch_any-stack_a243a85f.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "24be57783860925252a86e019a5215b871c0e86ed7c5b2a4eea15946d44a9956"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "7f4c08d414e794cdec71220956aa15821a8d491ec8d35023178357c9a94b1d7e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.96_linux_noarch_any-stack_24be5778.tgz"
    version = "0.0.96"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.96"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.109"
