api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "dfc7399afc4d3998123980e225975c404b9ef862874c0364fbbd66fc11091891"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "1f5ae0dc9b87b4b852d176163510373162e0f2f9f148048182745d55d199f09f"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.56-any-stack-dfc7399a.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "7cba59deb7ebb3bbe83332bf5e40cd0226af01ca8228406f5420c88431a4198f"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "7afb59ae5ceffa4f8c8ddc9422eae69e4e58c9fd5ef83f67aaaa66110695eda0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.61-any-stack-7cba59de.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "7cba59deb7ebb3bbe83332bf5e40cd0226af01ca8228406f5420c88431a4198f"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "7afb59ae5ceffa4f8c8ddc9422eae69e4e58c9fd5ef83f67aaaa66110695eda0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.61-any-stack-7cba59de.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a5dd5606c806f9637c20f041b444dd7b5d453ab27dee17bc3a7405049dd6fa12"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "935778a43268ff1f209c0756cc09a89ca04b1bdf47c66fca34cbb602b91e48e7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.54-any-stack-a5dd5606.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a5dd5606c806f9637c20f041b444dd7b5d453ab27dee17bc3a7405049dd6fa12"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "935778a43268ff1f209c0756cc09a89ca04b1bdf47c66fca34cbb602b91e48e7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.54-any-stack-a5dd5606.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a5dd5606c806f9637c20f041b444dd7b5d453ab27dee17bc3a7405049dd6fa12"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "935778a43268ff1f209c0756cc09a89ca04b1bdf47c66fca34cbb602b91e48e7"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.54-any-stack-a5dd5606.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "7df8a8d4571ec2130a369dda5a5cd0e1c71f7c0c0e611d90178fa690eb71575e"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "91341c273b6256fdccabd3016eecd66798cdcd8563d8e5463e94740ea05c81e0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.49-any-stack-7df8a8d4.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "ad695cfb2e9d6d03b66ab54a435ec749f50b16e36bf180dbd1f04ccb1dc894dd"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "12482867863c5e968ef61c53ee28893637d5bf503707ac3f9ce4de059eeb3492"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.56-any-stack-ad695cfb.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "ad695cfb2e9d6d03b66ab54a435ec749f50b16e36bf180dbd1f04ccb1dc894dd"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "12482867863c5e968ef61c53ee28893637d5bf503707ac3f9ce4de059eeb3492"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.56-any-stack-ad695cfb.tgz"
    version = "0.0.56"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.56"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.61"
