api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"

[[order.group]]
id = "org.cloudfoundry.go-mod"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"

[[order.group]]
id = "org.cloudfoundry.dep"
