api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "f6c574807e441e4547f1bb2d5ec20adac9d7133aafebec435c46a70b62275040"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "eaaf4bb8464fb6f2ca61e02fafd943d7dc2b2f4e1ebc8d635aab5f9caef08f5a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.88-any-stack-f6c57480.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "4a52b808ea6a2a1eea39c2bfe7adb4167ea152f37202f69b17af66f75a919f23"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "aa56b57a4ed5255214c1bb779e4e26da3f33a116cb4f750652d40dc6b7298bf9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.81-any-stack-4a52b808.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "f85721a11d1f363e638267e3f6a78f0d8c1ac31bb29f499df6885de71b29ccfc"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "928572161625e5fde39505d414586770988323076df40bc6fd17a3b66d0ff1c3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.83-any-stack-f85721a1.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.81"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.81"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.88"
