api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "d9c61daaae301975d055111211ed7e5cc932aadc03becbd162256fb7d66d2649"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "de063bb5418a30e12e5d3271f4aecde34c588f8db371ed01f0ea3863c5314d87"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.83-any-stack-d9c61daa.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "dadca0eae2ac83fc09c6c6887bf2c0872b7b2bb0215079eae88ee325fec0af57"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "61fc5c439ccea1b1b20c7d6147d55622da264fe65658d9f461a6c36828c3e47b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.73-any-stack-dadca0ea.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "c2d304a7333d9b6539e80468da734b8b4dcf114770f8d2443ed59a5abf81c361"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "bce7c7f0ee6012b9dae7ac7034d2cdedad9f2f86b7e0a2506fe6bdaf03989c9f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.77-any-stack-c2d304a7.tgz"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.83"
