api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "2e96ead384d21e791f8292a1995e93750ebef8215e76fab3cae89175f9ae6bad"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "4d1beb13a1b019367659ff04ea9ecfc3c3af69046009d63bcd7a2698c3557635"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.46-any-stack-2e96ead3.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "c336e16c56f75fb9fd88328728da416a140533e3610ca7483ad1042182d836dc"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "937e87ebad348e0fbfa520e16a5cba22037fe425aa469ef363008eb37e8b7c86"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.42-any-stack-c336e16c.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "c64c20a29ac74ef5c83561328dc50b917a77d93d732704a4b22a424a910d6cda"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "4707c1861e0637ac91922546e8ef71ce77ad24af96125ec1b477f7b9f5cc0fb2"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.40-any-stack-c64c20a2.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.46"
