api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "4ee097eb20e500c6e27bb519ac74e7375f9491470c0017f0210b6c3670edeed3"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "c774c2a8b941cf26779df8d4fbd79e3e71b6f1e6e021feb3ab7e43dd7e032260"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.45-any-stack-4ee097eb.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "5632bc952dfc9073576adffef5eb5d0a116658bed8905fb347bdbde0bc797ba7"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "de091958da904431e88ef0b87eb84ca800e1dfbbdb94736141f9c95fd9416a7d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.40-any-stack-5632bc95.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "dcb9f6041083cd900583107996ed174affe53e665adc5f00ee0597fa0e4fea1e"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "ba7a986a17a1dc8f5e79f04c500e33e535fef7854a347d0e0c50ac71a53e3919"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.38-any-stack-dcb9f604.tgz"
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.45"
