api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "17716817f0099d2506c49fbc79e435664f36c15af8c3a7609c7e33bb74be10cd"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "cda57735b2abd85edd53b0c3c30822b5d7e2aba74276d53f0343e251b6ddc02f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.70-any-stack-17716817.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a11355e8e6b2d55ad61fab435dae8690f4c91f578f0784a0a9dc11d7c654e701"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "4b7f7ce39dc5998a311ede1242eb93973634c53b45410e886c4828ff95dfcb4f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.58-any-stack-a11355e8.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "d3ffd607d0f8b51f0ec3421cd6b6a1f304334335b680c5cd9dfdfbcb512c8a47"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "a328d89d44fcec84d5e5a6483178799fec93f2ce4a6a62920aaacea0e52b8b9e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.64-any-stack-d3ffd607.tgz"
    version = "0.0.64"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.58"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.64"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.58"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.70"
