api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "be1283e37adbcfbd1deb2527cae184be142f39edfb54f06696d4f5845376a3c0"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "f6c9a618a19ac53d2f4624a56c1b6492f0069835cbec878c98c0a232ed6e12ff"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.69-any-stack-be1283e3.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a11355e8e6b2d55ad61fab435dae8690f4c91f578f0784a0a9dc11d7c654e701"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "4b7f7ce39dc5998a311ede1242eb93973634c53b45410e886c4828ff95dfcb4f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.58-any-stack-a11355e8.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "dd689558c4d141da640cce1f9d95aaac5ddc39599a4afee3d47d73f6f44c4cb4"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "bb52fe4774a86a624327a922a32853748cf702c49e8d1a8191d2911c1c3736c0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.63-any-stack-dd689558.tgz"
    version = "0.0.63"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.58"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.63"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.58"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.69"
