api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "793ad8ddafccf3fb049040c3887d49aaea08f769c680a337d6a878a746f57fd7"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "4841f6516675ef7b06ef40c58517ac0ccd5fa5b9b1ef9dbc6c694a496267f624"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.75-any-stack-793ad8dd.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "bfa62904948ee04b6a536abd6ebe2853a438c71ceea270d8b3799c017f7fcd10"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "1a69b4101aaa9b720ed7c780df875776416b3509e71e631e84af812bf289b8c5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.65-any-stack-bfa62904.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "0b3f0f3416fdb9da3ba738dbcfd9945b9a47c4490329d14ad9047872eac4eacb"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "a42ca84068d5ca7fe7e2aa3d7c059a8b24fa60307657bf0c2d27776691e7a3aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.68-any-stack-0b3f0f34.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.75"
