api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "215f632990ca49506032852de180f002bf404903479f8b45f17609e2410a0d19"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "32cd34e727ed5d102df00c82ef8b18ab4753ee66b65088f62b569693b488efb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.106_linux_noarch_any-stack_215f6329.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "65285d803f8c284a122359761aebc673fd8776293b29f756a29f4046450777b5"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "c158597c6cbb27e405e1291d7e54652ce199aaae190321b675ae38c33cd87f15"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.110_linux_noarch_any-stack_65285d80.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "531340dbceef473e5a0a50269ab233c6b30ec5154f07f38e8f1b01a0c9769f80"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "a1a83c3f85f62950140b37b0c248111aa0e684dac94d83f5862d8a445f0d9f6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.94_linux_noarch_any-stack_531340db.tgz"
    version = "0.0.94"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.94"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.106"
