api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "6a32dc3be9b8ea7346dafeb8d0d144dfa90a8246d3a7d7a5cba18fcfa5bee68d"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "91094eb7d1ee1ba40e1d19577a1a913aef1acc46b7cefbe3ab4b9aef7e5e992f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.77-any-stack-6a32dc3b.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "e4f85f4eceec76b797d5abf635a8d7aa460a3f55ecc1ff78503ded79a1a6dc28"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "35fb90caa8175d230a27b130aa2760e7d7cb130c80bb0f7b40afb0adae2c3a86"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.68-any-stack-e4f85f4e.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "92599bbcc9444f6dcb64ed95426dd7547cddccf4cb91dfacd8647d4b77624f60"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "7820de9359a4cb4d25a76eb5ccce1c8d80240738c610903a742e95694920e7b7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.72-any-stack-92599bbc.tgz"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.77"
