api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "f6c67630f2e71f2789c8945a9993f00c52126685b868aafc636e8440de41b0dc"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "78d1784eb7d5d05f59c261049802222c2ddabc412948882ca5a15c14640d1fab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.68-any-stack-f6c67630.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "110486f7511598c6569f9bb88501b308dbb044a292dbc71e3607e701f0ccfe9c"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "03a4687aefaa59c0cfac798ff376f56058433921c09ea71003abd5cdc9f2de3a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.57-any-stack-110486f7.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "7602d07eaf8f9b2eb15cb5c5f319aac834f19826621a0e1def7920bf3e50bf5b"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "408ca30d348a8bd00de2a52c4ec83e833bfaa698030477b6e6f34181449530c7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.61-any-stack-7602d07e.tgz"
    version = "0.0.61"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.57"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.61"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.57"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.68"
