api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "c6f06881841b9860e64fa5bddbe7841b7d91067ffbd8ce1663daa3815915faa1"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "8c68da6d2cda0fb925a1aab520e6f9553e2a72eca73586e17fbfe1c272a7643a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.66-any-stack-c6f06881.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "110486f7511598c6569f9bb88501b308dbb044a292dbc71e3607e701f0ccfe9c"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "03a4687aefaa59c0cfac798ff376f56058433921c09ea71003abd5cdc9f2de3a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.57-any-stack-110486f7.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "e87a09e31d25ce50ae4fdef43bb54fec25888b1865d4f9e0f541cb74b1b01a44"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "e5661b088493897462f46820241b47419273a170345a964a40033984e7827930"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.60-any-stack-e87a09e3.tgz"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.57"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.60"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.57"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.66"
