api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "0bbd2288464e3aac213df682837898841dc1c8e313f7b9aafd0bc14aa073fd25"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "9d6f2ecf10ac5eaf6f421b3ecd990bd2eb9a510bdd7561335364206291379aba"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.81-any-stack-0bbd2288.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "395fcf0546f956c21e476aa66134d11e62eb67d375a48b8df125b88616eddfbc"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "3fabf946cf763107709aa81fffa30c59b5e49c43f8c98532fbb3629d9ba0674a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.72-any-stack-395fcf05.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "1769c8d03cf12c00af985b3996ee40f0219e76d8501123977d580446beee0cec"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "251d988c3a8a1124d66bef3c9d001a6a74972fb7e767dc8d09d7def39bd9196e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.75-any-stack-1769c8d0.tgz"
    version = "0.0.75"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.72"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.75"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.72"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.81"
