api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "ef7df11bfbae340886637b2a39fabe47ac9e781ccdcf6821f926ab58e32630f8"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "147bf2508910d5914b50cdf45f54c035a91ac9ed41a757d5ac8b607b4cc5cbc4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.108_linux_noarch_any-stack_ef7df11b.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a243a85f507ee9bf8f9c9e24f521362816e1f0b5204a724861066ab3953b77a8"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "22c8df59a80cfc5b53973f32412b4917f3e1d689f3801e588430bd7ec6afb1d6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.111_linux_noarch_any-stack_a243a85f.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "7d6ccca873a29d7e29ecdf7468d1f8fad010c8fd5ca7120994d61030854e449b"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "af3ef08c8991933b5fe4f5d86909648974b5b1113520435ca64041906c499a7b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.95_linux_noarch_any-stack_7d6ccca8.tgz"
    version = "0.0.95"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.95"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.108"
