api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "ae325a290ef48a1464a93826296acbfd1f5074ad59c98ad579759af5aa772bd1"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "a1158f0311c558f206a63576614b62f0529b35ee828c8a5943801f1405207f8a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.86-any-stack-ae325a29.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "6dbdc33d6206a65258b8697e72496c304a4a6bdc73e82e67102e6e272876a07b"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "9ac7db111e083af655999baed3868ddb57ddcaef6c739f47a508419620a9783a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.79-any-stack-6dbdc33d.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "8ea039415e9d6692ba9734812f24a77627f32aa60dcc4f85bd4644b55d466444"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "82d2d1906550160de8bc7b0073c91e190e8caa68d05196ffaf315e11b6264e3e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.81-any-stack-8ea03941.tgz"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.86"
