api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "dfc7399afc4d3998123980e225975c404b9ef862874c0364fbbd66fc11091891"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "1f5ae0dc9b87b4b852d176163510373162e0f2f9f148048182745d55d199f09f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.56-any-stack-dfc7399a.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "7c7c9b4326747a085c331af09dab13cd25635346ab42bc97c132fff4196e90ee"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "b8e35a74c2f8c6f80270fe2595d519334b2daba1576d48abe41b94ca638c596f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.50-any-stack-7c7c9b43.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "9a9f397f6ea4a1dfac4ec02d9b2d0b34fd216ec8eab78f75c9ccaff143a6278c"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "c629d45b7318f8b863b07a2851d5f4c177604b0c395ca72900aa974a40fb84ac"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.48-any-stack-9a9f397f.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.50"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.50"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.56"
