api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "dfc7399afc4d3998123980e225975c404b9ef862874c0364fbbd66fc11091891"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "1f5ae0dc9b87b4b852d176163510373162e0f2f9f148048182745d55d199f09f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.56-any-stack-dfc7399a.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "981b38c07d703eef0c5c0b96115fdd38af4fd8eff8768ceb22b10ade5ebe2a50"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "3c37f2d4c9ebf969b48d029dca3de582704d3f6f74c048d2cd4f95d1458ee114"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.51-any-stack-981b38c0.tgz"
version = "0.0.51"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "7df8a8d4571ec2130a369dda5a5cd0e1c71f7c0c0e611d90178fa690eb71575e"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "91341c273b6256fdccabd3016eecd66798cdcd8563d8e5463e94740ea05c81e0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.49-any-stack-7df8a8d4.tgz"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.56"
