api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "fcd89a216e911e2244e643c0c8777c3903d5c32100805d336d24aa5eaa58659d"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "ad3301beaad409ad8c8383673ed66ca24997b04747105e17af4b7fcf7fcd5b05"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.48-any-stack-fcd89a21.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "0bb5a340f3ffdd88a689bec886960007cd557d19760e406a39e47435a9377a3b"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "fd9392f330c2e6b2cb30f9bb17e1e25f9fd36279df9ff92483b5f6e67384ab5f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.45-any-stack-0bb5a340.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "dd2b34b2694abd0be524165af9be68e1a17e3fc0e42ddd4cf1fdb616e7526d28"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "54290b0e8fec6f550954e76ae8b98c51b61860b6d2add3bec973191ef3851b55"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.42-any-stack-dd2b34b2.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.48"
