api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "7372d754c541277a974e4bd4be2e7c8c126606dcc9e3865ba6a678d2d6d231b5"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "b720e39f2bc894adbf8ffffe2d6f92c88a7bbe485e5ba8ba7356032e1848c8ad"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.34-any-stack-7372d754.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "b19640bc591b0749b13b845ea641f44ba0b520cd438053712421d4b4feef2b68"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "b2755846766736f22e669ed4332c46d5237b9c2aa1ab68ea0f7c85bd0f53f25a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.35-any-stack-b19640bc.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "7ddf99cafeb534d0b4c6b963b03c01d202b8dce0429d3b765fc48208a5c1b621"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "6bcaa7d1f2ecb1fb8de086a0f93943ed1f743f16d40f15da245e2e9e874c40f7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.34-any-stack-7ddf99ca.tgz"
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.34"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.34"
