api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "62a67f7c1a67334be7480d079fd33261fa3195d676d4530487f09322ec2ac5a2"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "a4cf55aff5795b290e6f7763cc9c65196341f5528ceaab528ddd7ef872e3b1dc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.87-any-stack-62a67f7c.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "9ccc069f21e6e27cdb891da7502cc81a8faa1fcd5d8dc28d7eb3e35a7bac8506"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "69dca136df0c115f43202649089b73c02d26c7c791c4510a8074ed59c124ec32"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.80-any-stack-9ccc069f.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "f85721a11d1f363e638267e3f6a78f0d8c1ac31bb29f499df6885de71b29ccfc"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "928572161625e5fde39505d414586770988323076df40bc6fd17a3b66d0ff1c3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.83-any-stack-f85721a1.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.80"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.80"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.87"
