api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "d501ac1a5cd88fabec74bbd28d6147739b0c9cf33706ca4d0737b96e0848b457"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "6d76198ed358adb97492e7e30cfc5328bb103d97c87a4452ee549471e224899a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.39-any-stack-d501ac1a.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "2f6b9145b977c49cbe39ddfd32e093b3658ddd874701ca88774d03c33b0e5920"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "88283109d97bbb492e79f6beb3c7a794c52a3b088c19ecc09e90691825c39da1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.37-any-stack-2f6b9145.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "f58c188e3c6662da7bbef5728b0def042d0ec234e1d93e14108b9e037892fe97"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "62f53d9266f74afe5f7f116551fe4b58f887cd1fbfcaced06dc40e0f98831f3b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.36-any-stack-f58c188e.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.39"
