api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "b634b6a812911caa59963263216a3e8f2b347f795f485254863bd7bd59ad519e"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "4d85dd7ad472ce5903a838d4998dc8723cc3b3ebea132026fae023806b567b5e"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.53-any-stack-b634b6a8.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "3930fb5e9168a7cfb9c97d8d5331f190261ab265a997bd87dd41e8eaeb8ec5da"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "697d8cba1074add729ace87b40e271bf01cae19f3d308b75bdb67069707663ea"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.48-any-stack-3930fb5e.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "e5eddd6fe38967d8f62766681b1d486b18c96aa373b9658e837d219bcb2289e0"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "7e8e82253a8738fff9434c1cbe48928b15019e0241a0ab97331499b4b10bc033"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.45-any-stack-e5eddd6f.tgz"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.53"
