api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "9ffa4726c303482a904ff6a234ac391f38a6b3c1e1ae902e4c83ed81c19f531a"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.28.tar.gz"
source_sha256 = "c684159ed727e1c8ee5281a6bfc6f980cef7c707c165752362fb6e12b16804f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.28-any-stack-9ffa4726.tgz"
version = "0.0.28"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "0f68cdd484e5903c31848aff7f489899c5b4eb059a0dc357dd0d225c5a3a2010"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "6a1224a0bdcfea5c7fc6721ed16ff581ecb7a8e4e7d11e8c49c8e4ecc4586006"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.30-any-stack-0f68cdd4.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "27609604cf9ac8ca10f5996c442d006cb021b0d795162fe5c6b29f704f9bd72b"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "6b1ec0836d7383d884ea34cc589bd901d92d2f2bd372083e7d5caf023ad655a0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.29-any-stack-27609604.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.30"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.30"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.28"
