api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "dfc7399afc4d3998123980e225975c404b9ef862874c0364fbbd66fc11091891"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "1f5ae0dc9b87b4b852d176163510373162e0f2f9f148048182745d55d199f09f"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.56-any-stack-dfc7399a.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "2d775a1b88d63c0c93d4bb2b97e80f104d57e14a884547ca03b03b5bf6ea83c9"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "15808ef7648fa018083975447f21ec55eb120b5395de21af9ce3e1bd52b5b102"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.60-any-stack-2d775a1b.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "2d775a1b88d63c0c93d4bb2b97e80f104d57e14a884547ca03b03b5bf6ea83c9"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "15808ef7648fa018083975447f21ec55eb120b5395de21af9ce3e1bd52b5b102"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.60-any-stack-2d775a1b.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "4ec960293d197ed7bc8208fb25468995a2092ae0570f36b8c5f7b586c85e7a35"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "a758827b24c2d370ee1bdfb9e6c70a0b764969d95ca2a112805bec758f9125d0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.53-any-stack-4ec96029.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "4ec960293d197ed7bc8208fb25468995a2092ae0570f36b8c5f7b586c85e7a35"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "a758827b24c2d370ee1bdfb9e6c70a0b764969d95ca2a112805bec758f9125d0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.53-any-stack-4ec96029.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "4ec960293d197ed7bc8208fb25468995a2092ae0570f36b8c5f7b586c85e7a35"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "a758827b24c2d370ee1bdfb9e6c70a0b764969d95ca2a112805bec758f9125d0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.53-any-stack-4ec96029.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "7df8a8d4571ec2130a369dda5a5cd0e1c71f7c0c0e611d90178fa690eb71575e"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "91341c273b6256fdccabd3016eecd66798cdcd8563d8e5463e94740ea05c81e0"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.49-any-stack-7df8a8d4.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "b416dbc77820297fc0ab127436ed7dbd6d41864270802d2ead9ec3ebee224644"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "d839fc27ce24a814d965dda71117f8c5bf0df212f03cfc68c9650077d519d850"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.53-any-stack-b416dbc7.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "b416dbc77820297fc0ab127436ed7dbd6d41864270802d2ead9ec3ebee224644"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "d839fc27ce24a814d965dda71117f8c5bf0df212f03cfc68c9650077d519d850"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.53-any-stack-b416dbc7.tgz"
    version = "0.0.53"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.53"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.53"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.53"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.60"
