api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a3a4c23943618d76f01d21a38715f7417d5b03282eb2cc56f43c65737208a85b"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "41a6b41f3f2324ead114ecdf4e5133bd1cda1c6ff96f0bea92d203c3adb68e39"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.101-any-stack-a3a4c239.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "e78e01f4cf449108bf46a17a57fdd64205ed18ff0bc0d507c9ffa964c90a0b73"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "83510e2eca0fdad598696b3c63737523e0ffb3749631a16c625570a5b81b0d54"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.105_linux_noarch_any-stack_e78e01f4.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "d4160af9e48fabc90c4e63ccd060f59988ec73c6fbb1bcea58b803a72d10b468"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "21e9a8168b4ed658404637fdc3d1ab3864223f8237659e63e8da0295d9199200"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.89_linux_noarch_any-stack_d4160af9.tgz"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.105"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.105"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.101"
