api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "3c53b7efd8458d42dd32f68b57ded4321f6c7f9e20008c78bd4aa0dc88d064aa"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "8e536e247506ccef217f98abb07729843cb6f2f29ba6b4c74e9a90bb06b4752d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.76-any-stack-3c53b7ef.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "93a5c437fb573f9fdcb3e05cb29f081f8eacb2cf21b7624e83f2574bf0806763"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "a7fe0f524bd2e11fda99876b22988654693877c7acccc81d5477cc3f76330940"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.66-any-stack-93a5c437.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "32c129c7f6c8ac2b52783a7ef58dd518a11cfa9072ced8f20146cc7b2c17df54"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "e4ab6411052766223d4841b771bf2d2460283971b440ee98ea7cdbd668439b4a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.69-any-stack-32c129c7.tgz"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.76"
