api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a3a4c23943618d76f01d21a38715f7417d5b03282eb2cc56f43c65737208a85b"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "41a6b41f3f2324ead114ecdf4e5133bd1cda1c6ff96f0bea92d203c3adb68e39"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.101-any-stack-a3a4c239.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "ac32d8a1da39278ae73683b2e5b2c0ee3d92d6598c0b41b3c8bb8145446ecb7e"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "76da194eb9b29bee3a31cb4d31712734a3a68cf54ac739402252df3964e3006b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.102-any-stack-ac32d8a1.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "bb4fd723ccc92fbe1fd261c3d71682bda85da9e1d603e1e3bc2efda509f0eeaf"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "a882d92c711c121b6e8f8c6c91ae8d1c51cea1f781b02c11bd772b989540e36e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.87-any-stack-bb4fd723.tgz"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.101"
