api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "7f3467a37092462e7cbe45cb79ec85c37ad668023c6a0d017b7da3281d42977a"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "000589a9df7052112ea1025eb973a0b0768b8cf18ac44fed8725a2e2c8fe5558"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.84-any-stack-7f3467a3.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "dadca0eae2ac83fc09c6c6887bf2c0872b7b2bb0215079eae88ee325fec0af57"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "61fc5c439ccea1b1b20c7d6147d55622da264fe65658d9f461a6c36828c3e47b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.73-any-stack-dadca0ea.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "66064af1b8348625dee76c8a9061da4ff216049c063fb69912db9896c467fd25"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "232f63d8a8053ce3fc7c6300efe9885c5be44de48eda3515d233d045627281da"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.78-any-stack-66064af1.tgz"
    version = "0.0.78"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.78"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.73"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.84"
