api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "e425cd44f094524af4e3bdd429ca8c1ba5aff5fd6bebefecca1b5ed02bdabed7"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "da1b551f8006d26a2ceda1893bac29bd5bcd1b261bbcbb9618ab2ff322f5161d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.91-any-stack-e425cd44.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "05acdafce73d576ee036370b426628b3e6051e2b1419a166b4f77607fd55f4ce"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "246d684496b51772c964b811cb2fe112483c464a00e27afe244562d6db2fee6a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.85-any-stack-05acdafc.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "2cc28d64e2ee1954755532699db3acd55ab25282af0c05a7f075bddcb400c836"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "19cf73ee26a0c2dd7cc5b1b69868a2fc57c978151be8d6616cd1fc04de9c206b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.84-any-stack-2cc28d64.tgz"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.85"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.84"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.85"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.91"
