api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "2b06dfaed9a3578e7ff704256fca2704ea88a7a26273d2895245968eb3524283"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "bc5f7b4706ad7e58540ba04747e7f61f814290eb6aa247416db0971cb021ff97"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.55-any-stack-2b06dfae.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "40b0f318c3b8669eabe3d58a431e45bed355d30d55fc463601dfa7b82420c351"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "2abb6750e36379ca45321fd437a2174a8c13b755a2bd562e1e2294af4eef873e"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.49-any-stack-40b0f318.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "1b56863cdeed68ef4db8567d0a20b133884900157b46434a85fa744cba69546d"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "bcb0e6b7e92e6604ec4d89079c97a09cd11bdad6d56c32ff3fb6a9c46baae8f1"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.47-any-stack-1b56863c.tgz"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.55"
