api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "dfc7399afc4d3998123980e225975c404b9ef862874c0364fbbd66fc11091891"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "1f5ae0dc9b87b4b852d176163510373162e0f2f9f148048182745d55d199f09f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.56-any-stack-dfc7399a.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "109c80eb7eb583cd2be8fbf5b92dee8fe72abd6ea3ea832b20c67fa7b8a6aa19"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "34abe8806a78fbc73d3ca8d4b7698cdc52af69d2dc48593fc9417f1cd356f5b8"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.52-any-stack-109c80eb.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "7df8a8d4571ec2130a369dda5a5cd0e1c71f7c0c0e611d90178fa690eb71575e"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "91341c273b6256fdccabd3016eecd66798cdcd8563d8e5463e94740ea05c81e0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.49-any-stack-7df8a8d4.tgz"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.56"
