api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "e14ba5c2d20fdc6e75a22e7e3653b54da8826ab10b6be93ad63b3251cd6c3e4e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "7abc732a7e0d5c6f73763b42ba4d74fcbe4878f2163d46dade04907910d521ba"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.104_linux_noarch_any-stack_e14ba5c2.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a2e64ed7d58506c1d0f53e3f825d3c97375b773521c8d5ef983e693095a8fa3e"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "5711a4de4526affca4583d61a5f89446f8d2290f675a9392681c6efc0fc07cc9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.106_linux_noarch_any-stack_a2e64ed7.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "1a870349fd24f0b28d787d76d66bca05ea9bad256a0fef780c4bee1afbfb4699"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "6b7e32dd29a6b1d4696aa99f3515524f192fa24055240e266546cce0fe9315a6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.91_linux_noarch_any-stack_1a870349.tgz"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.104"
