api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "1abcb0c7731edd2509dbff9f6b556be2a0ece7e7d9f1788041803a38f3f8e8cf"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "868c5e6eee54daa8b252ea413f1d7872e514b6d290e431abaa4ac9887b14614e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.29-any-stack-1abcb0c7.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "308d0c840744426b5769add7ba125326d148276e656f6e0cbda202101963aec9"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "4619028b0a0d5d529824f6cc0edba3a2866ed328e5cc6a65c9586800e3917f1b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.33-any-stack-308d0c84.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "67889dfea3fe2fb90f80213844b010e3e457a0b0c232eccf9d69066ae07e29df"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "529032294ca85a784de716aee5e87265b8bd25cc75093733ce2a8dc70829a02c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.30-any-stack-67889dfe.tgz"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.29"
