api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "b07b3d0979cd80c28f618c7716be318686b0bd8fb79217f1ae240f33268892c1"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "9044d7668e222d0a21f11e6d8a193a77735905208370750d430993ca27890346"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.79-any-stack-b07b3d09.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "795e25fa70c75746005079a7981d9d9022b56f7a40f5e9a5254d0001837a2629"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "af075a57e6cab5224e8516d59800aa0d520586d741dbf19203b679ca75a8b011"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.70-any-stack-795e25fa.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "aac19a9cfb9d1853564353d8f87bdc9aa5edd5314c0749dd015cced6cddd5c65"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "2c6f605b8bf22242dd912e2c32962ca87983d8380191d00cbf9836b94b1533ef"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.74-any-stack-aac19a9c.tgz"
    version = "0.0.74"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.74"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.79"
