api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "3b1ca21fc245d11612a355bf3dd99832d5fcd3f4cb34d3876a48423546c96083"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "bb8ef633809eabe41baa4048139effc4dcdfc0a989e014738e5b738f091125df"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.78-any-stack-3b1ca21f.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "795e25fa70c75746005079a7981d9d9022b56f7a40f5e9a5254d0001837a2629"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "af075a57e6cab5224e8516d59800aa0d520586d741dbf19203b679ca75a8b011"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.70-any-stack-795e25fa.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "550a75e9c31a7a527735b806a47ffe6b73e9b91b4fc54f68249cd77aba73ccb0"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "7af22a9d7be36fe83ee68668fd4ce0246ac3d5cd62b62eaf2f587ac48bb66191"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.73-any-stack-550a75e9.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.78"
