api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a90f9ca372f8714a1e86b1dc824987aa450a24d6c4eca91597882b6b0a2a0f2b"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "6d3da3776bd2789e3999922b74582fd2c0500e72afac5f1f958810494f8ad2f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.74-any-stack-a90f9ca3.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "bfa62904948ee04b6a536abd6ebe2853a438c71ceea270d8b3799c017f7fcd10"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "1a69b4101aaa9b720ed7c780df875776416b3509e71e631e84af812bf289b8c5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.65-any-stack-bfa62904.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "0b3f0f3416fdb9da3ba738dbcfd9945b9a47c4490329d14ad9047872eac4eacb"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "a42ca84068d5ca7fe7e2aa3d7c059a8b24fa60307657bf0c2d27776691e7a3aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.68-any-stack-0b3f0f34.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.65"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.74"
