api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "62a67f7c1a67334be7480d079fd33261fa3195d676d4530487f09322ec2ac5a2"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "a4cf55aff5795b290e6f7763cc9c65196341f5528ceaab528ddd7ef872e3b1dc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.87-any-stack-62a67f7c.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "6dbdc33d6206a65258b8697e72496c304a4a6bdc73e82e67102e6e272876a07b"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "9ac7db111e083af655999baed3868ddb57ddcaef6c739f47a508419620a9783a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.79-any-stack-6dbdc33d.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "9313d15126ab131463c2382956a88bed2d3e2dc8e4a9691776988a6e6b08f695"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "1f3ed7802453588d6d49c0f9dd9104694499a16868a3335ef580d710f7c64634"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.82-any-stack-9313d151.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.87"
