api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "1b512342d96d2b37818056d3ff0ea940dc57debb606d41c0b3ba75bb9e79f471"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "cfc44bf66b74121691951c81b072583c8ef56b8088723550f8062e7e7acf3647"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.80-any-stack-1b512342.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "795e25fa70c75746005079a7981d9d9022b56f7a40f5e9a5254d0001837a2629"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "af075a57e6cab5224e8516d59800aa0d520586d741dbf19203b679ca75a8b011"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.70-any-stack-795e25fa.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "1769c8d03cf12c00af985b3996ee40f0219e76d8501123977d580446beee0cec"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "251d988c3a8a1124d66bef3c9d001a6a74972fb7e767dc8d09d7def39bd9196e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.75-any-stack-1769c8d0.tgz"
    version = "0.0.75"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.75"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.80"
