api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "74457e92f0fc9127e925e86635360380f7c0dc9c740b5a24d8930ba7bc6d72de"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "5e2d36a74b802e748741ea5aaeb49206c70c8159ae977b995a382d30f8fc501d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.50-any-stack-74457e92.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "3930fb5e9168a7cfb9c97d8d5331f190261ab265a997bd87dd41e8eaeb8ec5da"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "697d8cba1074add729ace87b40e271bf01cae19f3d308b75bdb67069707663ea"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.48-any-stack-3930fb5e.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "dd2b34b2694abd0be524165af9be68e1a17e3fc0e42ddd4cf1fdb616e7526d28"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "54290b0e8fec6f550954e76ae8b98c51b61860b6d2add3bec973191ef3851b55"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.42-any-stack-dd2b34b2.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.50"
