api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a05db0c221b7366ac536b3c059b232fa68d42bb62984d5a80817180a07d507e7"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "c8a7319330549a79634b983d524ea56a2771d83bfb26d8db26bf1c71fa48f335"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.64-any-stack-a05db0c2.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a5dd5606c806f9637c20f041b444dd7b5d453ab27dee17bc3a7405049dd6fa12"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "935778a43268ff1f209c0756cc09a89ca04b1bdf47c66fca34cbb602b91e48e7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.54-any-stack-a5dd5606.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "863d2d1dd487936c1438fd396792df71ed6e780bc8de213433855dbc91d36432"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "3c91f6ad2843279f25aaedaab41268cb467920e62b00a065ec49e4f59681c05c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.57-any-stack-863d2d1d.tgz"
    version = "0.0.57"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.57"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.64"
dpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.57-any-stack-863d2d1d.tgz"
    version = "0.0.57"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.57"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.54"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.64"
