api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "20048ab3ebdfdc9e460821b4b9d077905468a4a05087dce2d3bac55feca139cf"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "e82164a72291529daa73d36d358c5ecc63baac498f417e5a1015507f5e6cc3ea"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.36-any-stack-20048ab3.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "2f6b9145b977c49cbe39ddfd32e093b3658ddd874701ca88774d03c33b0e5920"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "88283109d97bbb492e79f6beb3c7a794c52a3b088c19ecc09e90691825c39da1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.37-any-stack-2f6b9145.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "05ea1c65036812e6c8f07ee50c2dc51a4d9b9701b9ce7bec06fd17940428ce88"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "06465cfbd58aee1674c3c6d6c5db651443bd676187eda89812a5dcd3aebd9b07"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.35-any-stack-05ea1c65.tgz"
version = "0.0.35"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.35"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.36"
