api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "d8f91b5edcfd877ec8ae8e152570321c85f744bceab473cc0a1d0f2c5fb879db"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "de547ecb7e9f866977df20992685a3025eb747e289939f8270b8c8e2ffa7487a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.41-any-stack-d8f91b5e.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "f8ecea394f02f7ad4fbf3998009e6b74874a9a3068b2d77ee8f1fb40c516a1c9"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "eac7c1085120fb32be9fbbeb9e2c18090c29400d6658f25371a46f1af2642f4c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.38-any-stack-f8ecea39.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "f58c188e3c6662da7bbef5728b0def042d0ec234e1d93e14108b9e037892fe97"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "62f53d9266f74afe5f7f116551fe4b58f887cd1fbfcaced06dc40e0f98831f3b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.36-any-stack-f58c188e.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.41"
