api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "2e96ead384d21e791f8292a1995e93750ebef8215e76fab3cae89175f9ae6bad"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "4d1beb13a1b019367659ff04ea9ecfc3c3af69046009d63bcd7a2698c3557635"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.46-any-stack-2e96ead3.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "7659ae76e73db15d979a2c28641b7c80bb0546e0582cdc8b9718bdf2a0fe09b4"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "36eac094d239c43f03d16d207a81b100045c4e1ba0ebfa7da9293acb410972bf"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.41-any-stack-7659ae76.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "873b293f345960a0ef3b77eddb7461acc14de0b21ed5578d34efcd3330a9d682"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "6ef7b4bff30c709d370be75a5b655c869d650d78d16eb1782dcb28ce4a27c682"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.39-any-stack-873b293f.tgz"
version = "0.0.39"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.39"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.46"
