api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "6a32dc3be9b8ea7346dafeb8d0d144dfa90a8246d3a7d7a5cba18fcfa5bee68d"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "91094eb7d1ee1ba40e1d19577a1a913aef1acc46b7cefbe3ab4b9aef7e5e992f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.77-any-stack-6a32dc3b.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "7ddb88fa92890412db54ff91b5fb154ef78f51b29fa8b2b5559720c2ccd138bb"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "552a253c380d6e86dc1baa97e8a6cf8cfd49683be955482b4320456ebb1c1f31"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.67-any-stack-7ddb88fa.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "826495412c0894d23ddd4b5632d24dddea4fa35754a389eec78694957971c18e"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "9909722f50e3c818fc53a8088714b0dd46753d12feb04362165ba90250f3972c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.70-any-stack-82649541.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.77"
