api = "0.2"

[buildpack]
id = "org.cloudfoundry.go"
name = "Go Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dep"
sha256 = "3ab798964c2b76ac818864a3fde7227644a40558b5e52ea8f9b29110121884a6"
source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "ff2954ab65c67d78a69fc57d4e3503527b184d732e7fe05e68a6a707beff8ec3"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.49-any-stack-3ab79896.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-compiler"
sha256 = "deea7a52d94ebff94f3a8938884067340d7a310dc81c6de510a305a17246be72"
source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "2250efd5070e18d430090ac777b3e73f99a209cef7bb8889501a84151f685225"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.47-any-stack-deea7a52.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.go-mod"
sha256 = "dd2b34b2694abd0be524165af9be68e1a17e3fc0e42ddd4cf1fdb616e7526d28"
source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "54290b0e8fec6f550954e76ae8b98c51b61860b6d2add3bec973191ef3851b55"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.42-any-stack-dd2b34b2.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.go-mod"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go-compiler"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.dep"
version = "0.0.49"
