api = "0.2"

[buildpack]
  id = "org.cloudfoundry.go"
  name = "Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "384ba8afc37d2dfdba02aabcf4b406cc6c620b316239187ee3e6e03d86a2d184"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "15f041e226e5f0276ba3667d94fa16b1205df6abe527beb3944b5146495100f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.85-any-stack-384ba8af.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "e80046f9b224c2ed8cfd0c89543b99be8d1ffb7d6fad5ed2608820bf527a7736"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "60a64652fb56f037536463a1ad375101e1748ca5e9d1076d623fac39aaa0df0d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.76-any-stack-e80046f9.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "59a6ba007b7ed90b6be89f2352738682ec5afd3d227dea6aa93a2081ed9d59bf"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "14a0479dc5417d3f46c5275d8f8008767754bc1eafac4702a63f3a23bfb98330"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.79-any-stack-59a6ba00.tgz"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.76"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.76"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.85"
