api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "5f6e9c8d098bafbfff25d8fded416c1cabe0678111bf700b4b58966a1f4c0605"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "a774f8e4b8ca512e1d7cc7e6325c72e56751a3920b824fa6173a597ca472b708"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.105_linux_noarch_any-stack_5f6e9c8d.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "a2e64ed7d58506c1d0f53e3f825d3c97375b773521c8d5ef983e693095a8fa3e"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "5711a4de4526affca4583d61a5f89446f8d2290f675a9392681c6efc0fc07cc9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.106_linux_noarch_any-stack_a2e64ed7.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "059fddf42fb1980a9922e568291e41c354a0f2ced862c5b595b3aa819b8961e8"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "099cfa11af2e874eb35956366f038381c1733b9270ad6a53f4ac90b3e210ec25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.92_linux_noarch_any-stack_059fddf4.tgz"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.105"
