api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "87a496cdb068e84a5a0f68c4a69fbc225b60053e09b2c8e58866a15a1b05bbbd"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "8433b53885c5d81db995dd607656d5cd1ff7c9015dfc5a32452390ff7d1ed42a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.100-any-stack-87a496cd.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "500d55f6a8faa271842ef7d47270809cc7771268a194c901cc9846628d618d50"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "c879f5a21888d8c99991eb7ed0c1f52619f1ac0bd579063990765a27030e57b0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.99-any-stack-500d55f6.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "ae3608e8f3b5491a3c7577135b3e6eaba693621a11c9f4a3768c4c3e9bddacb7"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "ebef01cce9b301a727e94985516e467dea4c46c055ec72f407d8f5010cdb337a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.85-any-stack-ae3608e8.tgz"
    version = "0.0.85"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.99"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.85"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.99"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.100"
