api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a61c7dd8d13be140806c8b8ae520354650cb323aa7970ff33407cd7e70e791d5"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "cb3607b6772b425366526e8e0230aba5c943db4f74dd438da719826c63fc6821"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.96-any-stack-a61c7dd8.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "c2e4e17369d6890dc70aa1140ab4e033194fac670a10f2ad9f2b596b01926c81"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "7d4a042370a42737bb6f4061772c04d685c3474f52310ef3908105be2883ba2a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.92-any-stack-c2e4e173.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "fe15aa721fa712f9938eb2e1e7eff256faddfed2456beebe652e4632b9b7fc9b"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "b08e096458745bd8d4724a2f23eb52fba51a3cb6fbf176f596b8ce2479b4df16"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.58-any-stack-fe15aa72.tgz"
    version = "0.0.58"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.92"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.58"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.92"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.96"
