api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "e14ba5c2d20fdc6e75a22e7e3653b54da8826ab10b6be93ad63b3251cd6c3e4e"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "7abc732a7e0d5c6f73763b42ba4d74fcbe4878f2163d46dade04907910d521ba"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.104_linux_noarch_any-stack_e14ba5c2.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "e78e01f4cf449108bf46a17a57fdd64205ed18ff0bc0d507c9ffa964c90a0b73"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "83510e2eca0fdad598696b3c63737523e0ffb3749631a16c625570a5b81b0d54"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.105_linux_noarch_any-stack_e78e01f4.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "1a870349fd24f0b28d787d76d66bca05ea9bad256a0fef780c4bee1afbfb4699"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "6b7e32dd29a6b1d4696aa99f3515524f192fa24055240e266546cce0fe9315a6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.91_linux_noarch_any-stack_1a870349.tgz"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.105"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.105"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.104"
