api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "a3a4c23943618d76f01d21a38715f7417d5b03282eb2cc56f43c65737208a85b"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "41a6b41f3f2324ead114ecdf4e5133bd1cda1c6ff96f0bea92d203c3adb68e39"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.101-any-stack-a3a4c239.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "ac32d8a1da39278ae73683b2e5b2c0ee3d92d6598c0b41b3c8bb8145446ecb7e"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "76da194eb9b29bee3a31cb4d31712734a3a68cf54ac739402252df3964e3006b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.102-any-stack-ac32d8a1.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "d4160af9e48fabc90c4e63ccd060f59988ec73c6fbb1bcea58b803a72d10b468"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "21e9a8168b4ed658404637fdc3d1ab3864223f8237659e63e8da0295d9199200"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.89_linux_noarch_any-stack_d4160af9.tgz"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.101"
