api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "87a496cdb068e84a5a0f68c4a69fbc225b60053e09b2c8e58866a15a1b05bbbd"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "8433b53885c5d81db995dd607656d5cd1ff7c9015dfc5a32452390ff7d1ed42a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep-0.0.100-any-stack-87a496cd.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "10cca89ed87967bf59467b986472d972dde780d5a3c2d2be25cf644d03d0f670"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "c66f7c94d17962e1861b29b5c766750850b33cd0f13a04ddff96412ac56f50a1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler-0.0.101-any-stack-10cca89e.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "34b8acf294a7d36ab92575eb0b4fa334250d700126d20397e8f6604ea627b0ed"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "99ac081b75148214d71dd4580a2d99e7efdc6c4ea45903c70d9cb93410c4ae95"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod-0.0.86-any-stack-34b8acf2.tgz"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.101"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.86"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.101"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.100"
