api = "0.2"

[buildpack]
  id = "org.shim.go"
  name = "CF Go Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dep"
    sha256 = "215f632990ca49506032852de180f002bf404903479f8b45f17609e2410a0d19"
    source = "https://github.com/cloudfoundry/dep-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "32cd34e727ed5d102df00c82ef8b18ab4753ee66b65088f62b569693b488efb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dep/org.cloudfoundry.dep_0.0.106_linux_noarch_any-stack_215f6329.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-compiler"
    sha256 = "26acbbbc9f67007b878581403116a7224a10d56b1f779049cc8acd19377456c3"
    source = "https://github.com/cloudfoundry/go-compiler-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "209bbecee6d8d0d81eefa51bcd121eb586adb36344cec4f5a43bc014ccbd5066"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-compiler/org.cloudfoundry.go-compiler_0.0.107_linux_noarch_any-stack_26acbbbc.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.go-mod"
    sha256 = "351fa91ff2a730211aa3083d3239a7d8bdf08f85d71bb6d6e036b0cf6bb1cfbd"
    source = "https://github.com/cloudfoundry/go-mod-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "2e9d70051d320559639726724f365bd3018804fe8024a59c0cc1decb0fe0864a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.go-mod/org.cloudfoundry.go-mod_0.0.93_linux_noarch_any-stack_351fa91f.tgz"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.107"

  [[order.group]]
    id = "org.cloudfoundry.go-mod"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.go-compiler"
    version = "0.0.107"

  [[order.group]]
    id = "org.cloudfoundry.dep"
    version = "0.0.106"
